// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuEyt3Vlk-XNNiD31d7HipQh7ZuFV31Bc',
    appId: '1:173930722270:web:714e03e2396284ac62a34f',
    messagingSenderId: '173930722270',
    projectId: 'studentmanager-b3e39',
    authDomain: 'studentmanager-b3e39.firebaseapp.com',
    storageBucket: 'studentmanager-b3e39.firebasestorage.app',
    measurementId: 'G-XKZT9NPMJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvINucnk6IKUmiQOsmHYk4q25_Mtebg5E',
    appId: '1:173930722270:android:f42e373723704f7662a34f',
    messagingSenderId: '173930722270',
    projectId: 'studentmanager-b3e39',
    storageBucket: 'studentmanager-b3e39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgM_5hPSGEEvOJzj22fQXisFtqDUSIKhk',
    appId: '1:173930722270:ios:36b927c6240ba0d862a34f',
    messagingSenderId: '173930722270',
    projectId: 'studentmanager-b3e39',
    storageBucket: 'studentmanager-b3e39.firebasestorage.app',
    iosBundleId: 'com.example.studentmanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgM_5hPSGEEvOJzj22fQXisFtqDUSIKhk',
    appId: '1:173930722270:ios:36b927c6240ba0d862a34f',
    messagingSenderId: '173930722270',
    projectId: 'studentmanager-b3e39',
    storageBucket: 'studentmanager-b3e39.firebasestorage.app',
    iosBundleId: 'com.example.studentmanger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuEyt3Vlk-XNNiD31d7HipQh7ZuFV31Bc',
    appId: '1:173930722270:web:3b03b925d04a3d7462a34f',
    messagingSenderId: '173930722270',
    projectId: 'studentmanager-b3e39',
    authDomain: 'studentmanager-b3e39.firebaseapp.com',
    storageBucket: 'studentmanager-b3e39.firebasestorage.app',
    measurementId: 'G-FYE295VE1S',
  );
}
